Website/NewsSite/News/urls.py
from django.urls import path
from . import views

app_name = 'News'
urlpatterns = [
    path('', views.index, name='index'),
    path('sources/', views.source, name='source'),
    path('category/', views.category, name='category'),
    path('general/', views.general, name='general'),
    path('source_news/', views.source_singlenews, name='source_news'),
    path('category_news/', views.category_singlenews, name='category_news'),
    path('news/', views.general_singlenews, name='news'),
    path('contact', views.contact, name='contact'),
]

Website/NewsSite/NewsSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('News.urls')),
] 

Website/djangoWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsApp.urls')),
    path('news/', include('newsApp.urls')),
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Website/newsApp/urls.py
from django.urls import path

from . import views

app_name = 'newsApp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('sources/', views.source, name='source'),
    path('category/', views.category, name='category'),
    path('topic/', views.topic, name='topic'),
]

Website/NewsSite/News/models.py
from django.db import models

# Create your models here.

Website/NewsSite/News/views.py
from django.shortcuts import render
from datetime import datetime
from newsapi import NewsApiClient

# Create your views here.
def index(request):
    News = NewsApiClient(api_key='d7ea451af97842bcaaf40d479460dfb9')
    sport_top_headlines = News.get_top_headlines(category='sports')
    sport_art=sport_top_headlines['articles']
    sport_title=[]
    sport_img=[]
    for article in range(len(sport_art)):
        f=sport_art[article]
        sport_title.append(f['title'])
        sport_img.append(f['urlToImage'])
    sport_src = zip(sport_title,sport_img)
    sport_data = list(sport_src)

    tech_top_headlines = News.get_top_headlines(category='technology')
    tech_art=tech_top_headlines['articles']
    tech_title=[]
    tech_img=[]
    for article in range(len(tech_art)):
        f=tech_art[article]
        tech_title.append(f['title'])
        tech_img.append(f['urlToImage'])
    tech_src = zip(tech_title,tech_img)
    tech_data = list(tech_src)

    bus_top_headlines = News.get_top_headlines(category='business')
    bus_art=bus_top_headlines['articles']
    bus_title=[]
    bus_img=[]
    for article in range(len(bus_art)):
        f=bus_art[article]
        bus_title.append(f['title'])
        bus_img.append(f['urlToImage'])
    bus_src = zip(bus_title,bus_img)
    bus_data = list(bus_src)

    enter_top_headlines = News.get_top_headlines(category='entertainment')
    enter_art=enter_top_headlines['articles']
    enter_title=[]
    enter_img=[]
    for article in range(len(enter_art)):
        f=enter_art[article]
        enter_title.append(f['title'])
        enter_img.append(f['urlToImage'])
    enter_src = zip(enter_title,enter_img)
    enter_data = list(enter_src)
    
    all_articles = News.get_everything(q='bitcoin',sources='bbc-news,the-verge',
                                      domains='bbc.co.uk,techcrunch.com',
                                      from_param='2021-09-04',
                                      to='2017-12-12',
                                      language='en',
                                      sort_by='relevancy',
                                      page=2)
    arti=all_articles['articles']
    title=[]
    img=[]
    
    for article in range(len(arti)):
        f=arti[article]
        title.append(f['title'])
        img.append(f['urlToImage'])
    src = zip(title,img)
    source_data1 = list(src)
    return render(request, 'news/index.html',{'enter_data':enter_data[:4],'bus_data':bus_data[:4],'tech_data':tech_data[:4],'sport_data':sport_data[:4],'source_data1':source_data1[:9]})


def contact(request):
    return render(request, 'news/contact.html')

def source(request):
    
    selected_source = request.GET.get('source')
    News = NewsApiClient(api_key='d7ea451af97842bcaaf40d479460dfb9')
    sources = News.get_sources()
    top_headlines = News.get_top_headlines(sources=selected_source)
    art=top_headlines['articles']
    src=sources['sources']
    title=[]
    img=[]
    sour=[]
    for article in range(len(art)):
        f=art[article]
        title.append(f['title'])
        img.append(f['urlToImage'])
    source_data = zip(title,img)
    for source in src:
        sour.append(source['name'])
    return render(request, 'news/sources.html',{'selected_source':selected_source,'source_data':source_data})
    

def source_singlenews(request):
    selected_title = request.GET.get('source_news')
    News = NewsApiClient(api_key='d7ea451af97842bcaaf40d479460dfb9')
    top_headlines = News.get_top_headlines(sources='bbc-news,the-verge')
    art=top_headlines['articles']
    t=next(item for item in art if item['title'] == selected_title)
    title=t['title']
    author=t['author']
    desc=t['description']
    img=t['urlToImage']
    content=t['content']
    publish=t['publishedAt']

    all_articles = News.get_everything(q='bitcoin',sources='bbc-news,the-verge',
                                      domains='bbc.co.uk,techcrunch.com',
                                      from_param='2021-09-04',
                                      to='2017-12-12',
                                      language='en',
                                      sort_by='popularity',
                                      page=2)
    arti=all_articles['articles']
    title1=[]
    img1=[]
    
    for article in range(len(arti)):
        f=arti[article]
        title1.append(f['title'])
        img1.append(f['urlToImage'])
    src = zip(title1,img1)
    source_data1 = list(src)
    #publish = datetime.strptime(publish, '%Y-%m-%dT%H:%M:%SZ')
    return render(request, 'news/singlenews.html',{'title':title,'author':author,'description':desc,'image':img,'content':content,'publish':publish,'source_data1':source_data1[:3]})


def category(request):
        
    selected_category = request.GET.get('category')
    request.session['selected_category']= selected_category
    News = NewsApiClient(api_key='d7ea451af97842bcaaf40d479460dfb9')
    sources = News.get_sources()
    top_headlines = News.get_top_headlines(category=selected_category)
    art=top_headlines['articles']
    title=[]
    img=[]
    for article in range(len(art)):
        f=art[article]
        title.append(f['title'])
        img.append(f['urlToImage'])
    source_data = zip(title,img)
    
    return render(request, 'news/category.html',{'selected_source':selected_category,'source_data':source_data})
    

def general(request):
    selected_general = request.GET.get('general')
    News = NewsApiClient(api_key='d7ea451af97842bcaaf40d479460dfb9')
    all_articles = News.get_everything(q='bitcoin',sources='bbc-news,the-verge',
                                      domains='bbc.co.uk,techcrunch.com',
                                      from_param='2021-09-04',
                                      to='2017-12-12',
                                      language='en',
                                      sort_by='popularity',
                                      page=2)
    arti=all_articles['articles']
    title1=[]
    img1=[]
    for article in range(len(arti)):
        f=arti[article]
        title1.append(f['title'])
        img1.append(f['urlToImage'])
    src = zip(title1,img1)
    return render(request, 'news/general.html',{'selected_source':selected_general,'source_data':src})



def category_singlenews(request):
    selected_category = request.session['selected_category']
    selected_title = request.GET.get('category_news')
    News = NewsApiClient(api_key='d7ea451af97842bcaaf40d479460dfb9')
    top_headlines = News.get_top_headlines(category=selected_category)
    art=top_headlines['articles']
    t=next(item for item in art if item['title'] == selected_title)
    title=t['title']
    author=t['author']
    desc=t['description']
    img=t['urlToImage']
    content=t['content']
    publish=t['publishedAt']

    all_articles = News.get_everything(q='bitcoin',sources='bbc-news,the-verge',
                                      domains='bbc.co.uk,techcrunch.com',
                                      from_param='2021-09-04',
                                      to='2017-12-12',
                                      language='en',
                                      sort_by='popularity',
                                      page=2)
    arti=all_articles['articles']
    title1=[]
    img1=[]
    
    for article in range(len(arti)):
        f=arti[article]
        title1.append(f['title'])
        img1.append(f['urlToImage'])
    src = zip(title1,img1)
    source_data1 = list(src)
    #publish = datetime.strptime(publish, '%Y-%m-%dT%H:%M:%SZ')
    return render(request, 'news/singlenews.html',{'title':title,'author':author,'description':desc,'image':img,'content':content,'publish':publish,'source_data1':source_data1[:3]})


def general_singlenews(request):
    selected_title = request.GET.get('news')
    News = NewsApiClient(api_key='d7ea451af97842bcaaf40d479460dfb9')
    all_articles = News.get_everything(q='bitcoin',sources='bbc-news,the-verge',
                                      domains='bbc.co.uk,techcrunch.com',
                                      from_param='2021-09-04',
                                      to='2017-12-12',
                                      language='en',
                                      sort_by='popularity',
                                      page=2)
    arti=all_articles['articles']
    t=next(item for item in arti if item['title'] == selected_title)
    title=t['title']
    author=t['author']
    desc=t['description']
    img=t['urlToImage']
    content=t['content']
    publish=t['publishedAt']
    title1=[]
    img1=[]
    
    for article in range(len(arti)):
        f=arti[article]
        title1.append(f['title'])
        img1.append(f['urlToImage'])
    src = zip(title1,img1)
    source_data1 = list(src)
    return render(request, 'news/singlenews.html',{'title':title,'author':author,'description':desc,'image':img,'content':content,'publish':publish,'source_data1':source_data1[:3]})

Website/NewsSite/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>News Blog</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Bootstrap News Template - Free HTML Templates" name="keywords">
        <meta content="Bootstrap News Template - Free HTML Templates" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet"> 

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style1.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top Bar Start -->
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="tb-contact">
                            <p><i class="fas fa-envelope"></i>info@mail.com</p>
                            <p><i class="fas fa-phone-alt"></i>+012 345 6789</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="tb-menu">
                            <a href="">About</a>
                            <a href="">Privacy</a>
                            <a href="">Terms</a>
                            <a href="">Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Bar Start -->
        
        <!-- Brand Start -->
        <div class="brand">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-4">
                        <div class="b-logo">
                            <a href="index.html">
                                <img src="{% static 'img/logo.gif' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    
                   
                    <div class="col-lg-6 col-md-4">
                        <div class="b-search">
                            <input type="text" placeholder="Search">
                            <button><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
        <!-- Brand End -->

        <!-- Nav Bar Start -->
        <div class="nav-bar">
            <div class="container">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            
                            <a href="{% url 'News:index' %}" class="nav-item nav-link active">Home</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Category</a>
                                <div class="dropdown-menu">
                                    <a href="/category/?category=business" class="dropdown-item">Business</a>
                                    <a href="/category/?category=technology" class="dropdown-item">Technology</a>
                                    <a href="/category/?category=sports" class="dropdown-item">Sports</a>
                                    <a href="/category/?category=entertainment" class="dropdown-item">Entertainment</a>
                                </div>
                            </div>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Sources</a>
                                <div class="dropdown-menu">
                                    <a href="/sources/?source=bbc-news" class="dropdown-item">BBc News</a>
                                    <a href="/sources/?source=the-verge" class="dropdown-item">The-Verge</a>
                                </div>
                            </div>
                            <a href="{% url 'News:contact' %}" class="nav-item nav-link">Contact Us</a>
                        </div>
                        <div class="social ml-auto">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->
        {% block content%}
        {% endblock %}
         <!-- Footer Start -->
         <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Get in Touch</h3>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 News Street, NY, USA</p>
                                <p><i class="fa fa-envelope"></i>info@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Useful Links</h3>
                            <ul>
                                <li><a href="#">Lorem ipsum</a></li>
                                <li><a href="#">Pellentesque</a></li>
                                <li><a href="#">Aenean vulputate</a></li>
                                <li><a href="#">Vestibulum sit amet</a></li>
                                <li><a href="#">Nam dignissim</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Quick Links</h3>
                            <ul>
                                <li><a href="#">Lorem ipsum</a></li>
                                <li><a href="#">Pellentesque</a></li>
                                <li><a href="#">Aenean vulputate</a></li>
                                <li><a href="#">Vestibulum sit amet</a></li>
                                <li><a href="#">Nam dignissim</a></li>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Newsletter</h3>
                            <div class="newsletter">
                                <p>
                                    abcde fghi jklm nopq amet, consectetur adipiscing elit. Vivamus sed porta dui. Class aptent taciti sociosqu
                                </p>
                                <form>
                                    <input class="form-control" type="email" placeholder="Your email here">
                                    <button class="btn">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Footer Menu Start -->
        <div class="footer-menu">
            <div class="container">
                <div class="f-menu">
                    <a href="">Terms of use</a>
                    <a href="">Privacy policy</a>
                    <a href="">Cookies</a>
                    <a href="">Accessibility help</a>
                    <a href="">Advertise with us</a>
                    <a href="">Contact us</a>
                </div>
            </div>
        </div>
        <!-- Footer Menu End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright" >
                        <p>Copyright &copy; <a href="#" style="color: white;">News</a>. All Rights Reserved</p>
                    </div>

                   
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
</body>
</html>